/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SmartdevicesCreateRouteImport } from './routes/smartdevices.create'
import { Route as RoomsIdRouteImport } from './routes/rooms.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartdevicesCreateRoute = SmartdevicesCreateRouteImport.update({
  id: '/smartdevices/create',
  path: '/smartdevices/create',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIdRoute = RoomsIdRouteImport.update({
  id: '/rooms/$id',
  path: '/rooms/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/smartdevices/create': typeof SmartdevicesCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/smartdevices/create': typeof SmartdevicesCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/smartdevices/create': typeof SmartdevicesCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rooms/$id' | '/smartdevices/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rooms/$id' | '/smartdevices/create'
  id: '__root__' | '/' | '/rooms/$id' | '/smartdevices/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomsIdRoute: typeof RoomsIdRoute
  SmartdevicesCreateRoute: typeof SmartdevicesCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smartdevices/create': {
      id: '/smartdevices/create'
      path: '/smartdevices/create'
      fullPath: '/smartdevices/create'
      preLoaderRoute: typeof SmartdevicesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$id': {
      id: '/rooms/$id'
      path: '/rooms/$id'
      fullPath: '/rooms/$id'
      preLoaderRoute: typeof RoomsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomsIdRoute: RoomsIdRoute,
  SmartdevicesCreateRoute: SmartdevicesCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
